# -*- coding: utf-8 -*-
"""Untitled4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Phe3Sb8BoOJpdTb_5LVJbYRzrECnM-xs
"""

def factorial(n):
    if n == 0:
        return 1
    return n * factorial(n-1)

factorial(5)

def factorial(n):
  if n==0:
    return 1
  return n*factorial(n-1)

factorial(5)

def fab(n):
  if n==0:
    return 0
  if n==1:
    return 1
  return fab(n-1) + fab(n-2)

fab(10)

def list_sum(lst):
  if lst==[]:
    return 0
  else:
    return lst[0]+list_sum(lst[1:])

list_sum([1,65,45,27,88])

def reverse(s):
  if s=="":
    return ""
  else:
    return reverse(s[1:])+s[0]
reverse("sangam")

def reverse(s):
  if s=="":
    return ""
  else:
    return reverse(s[1:])+s[0]
reverse("sangam")

def reverse(s):

  if s=="":
    return ""
  else:
    return reverse(s[1:])+s[0]

def is_palindrome(s):
  if reverse(s)==s:
    return True
  else:
    return False
is_palindrome("madam")

def pal(n):
  s=str(n)
  if reverse(s)==s:
    return True
  else:
      return False
pal(121)

def num(x,n):
  if n==0:
    return 1
  else:
    return x * num(x,n-1)

num(3,2)
